#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.5.0
# from Racc grammar file "".
#

require 'racc/parser.rb'

  require "lexer"
  require "nodes"

class Parser < Racc::Parser

module_eval(<<'...end grammar.y/module_eval...', 'grammar.y', 179)

  # code will be put as is in the Parser class
  def parse(code, show_tokens=false)
    @tokens = Lexer.new.tokenize(code)
    puts @tokens.inspect if show_tokens
    do_parse    # parsing process
  end


  def next_token
    @tokens.shift
  end
...end grammar.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    25,    14,    23,    24,    14,    16,    17,    18,    19,    20,
    21,    22,    25,    14,    23,    24,    14,    16,    17,    18,
    19,    20,    21,    22,    82,    43,    81,    42,    15,    13,
    46,    15,    73,    26,    70,    86,    77,    28,    45,    44,
    15,    13,    25,    15,    23,    24,    14,    16,    17,    18,
    19,    20,    21,    22,    25,    29,    23,    24,    14,    16,
    17,    18,    19,    20,    21,    22,    70,    48,    50,   nil,
    14,    13,    75,    15,   nil,   nil,   nil,   nil,   nil,    83,
   nil,   nil,    28,    13,    25,    15,    23,    24,    84,    16,
    17,    18,    19,    20,    21,    22,    25,    15,    23,    24,
    29,    16,    17,    18,    19,    20,    21,    22,   nil,    25,
   nil,    23,    24,    13,    16,    17,    18,    19,    20,    21,
    22,    25,   nil,    23,    24,    13,    16,    17,    18,    19,
    20,    21,    22,   nil,    25,   nil,    23,    24,    13,    16,
    17,    18,    19,    20,    21,    22,    25,   nil,    23,    24,
    13,    16,    17,    18,    19,    20,    21,    22,   nil,    25,
   nil,    23,    24,    13,    16,    17,    18,    19,    20,    21,
    22,    25,   nil,    23,    24,    13,    16,    17,    18,    19,
    20,    21,    22,   nil,    25,   nil,    23,    24,    13,    16,
    17,    18,    19,    20,    21,    22,    25,   nil,    23,    24,
    13,    16,    17,    18,    19,    20,    21,    22,   nil,    25,
   nil,    23,    24,    13,    16,    17,    18,    19,    20,    21,
    22,    25,   nil,    23,    24,    13,    16,    17,    18,    19,
    20,    21,    22,   nil,    25,   nil,    23,    24,    13,    16,
    17,    18,    19,    20,    21,    22,    25,   nil,    23,    24,
    13,    16,    17,    18,    19,    20,    21,    22,   nil,    25,
   nil,    23,    24,    13,    16,    17,    18,    19,    20,    21,
    22,    25,   nil,    23,    24,    13,    16,    17,    18,    19,
    20,    21,    22,   nil,    25,   nil,    23,    24,    13,    16,
    17,    18,    19,    20,    21,    22,    25,   nil,    23,    24,
    13,    16,    17,    18,    19,    20,    21,    22,   nil,    70,
    70,    75,    28,    13,    39,    40,    37,    38,    33,    34,
    35,    36,    31,    32,    30,    13,    69,    74,   nil,    28,
    29,    39,    40,    37,    38,    33,    34,    35,    36,    31,
    32,    30,    28,   nil,    39,    40,    28,    29,    39,    40,
    37,    38,    33,    34,    35,    36,    31,    32,    30,   nil,
    29,   nil,    63,    28,    29,    39,    40,    37,    38,    33,
    34,    35,    36,    31,    32,    30,    28,   nil,    39,    40,
    28,    29,    39,    40,    37,    38,    33,    34,    35,    36,
    31,    32,    30,   nil,    29,   nil,   nil,    28,    29,    39,
    40,    37,    38,    33,    34,    35,    36,    31,    32,   nil,
   nil,   nil,   nil,   nil,    28,    29,    39,    40,    37,    38,
    33,    34,    35,    36,    28,   nil,    39,    40,    37,    38,
   nil,    28,    29,    39,    40,    37,    38,    33,    34,    35,
    36,    28,    29,    39,    40,    37,    38,   nil,    28,    29,
    39,    40,    37,    38,   nil,   nil,   nil,   nil,    28,    29,
    39,    40,    37,    38,   nil,   nil,    29,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    28,    29,    39,    40,    37,
    38,    33,    34,    35,    36,    31,    32,    30,   nil,   nil,
   nil,   nil,    28,    29,    39,    40,    37,    38,    33,    34,
    35,    36,    31,    32,    30,   nil,   nil,   nil,   nil,   nil,
    29,    39,    40,    37,    38,    33,    34,    35,    36,    31,
    32,    30,   nil,   nil,   nil,   nil,   nil,    29 ]

racc_action_check = [
    73,    64,    73,    73,    73,    73,    73,    73,    73,    73,
    73,    73,    70,     2,    70,    70,    70,    70,    70,    70,
    70,    70,    70,    70,    76,    21,    76,    21,    64,    73,
    24,    73,    50,     1,    81,    82,    69,    62,    23,    22,
     2,    70,     0,    70,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,    42,    62,    42,    42,    42,    42,
    42,    42,    42,    42,    42,    42,    46,    26,    28,   nil,
    78,     0,    79,     0,   nil,   nil,   nil,   nil,   nil,    78,
   nil,   nil,    61,    42,    75,    42,    75,    75,    79,    75,
    75,    75,    75,    75,    75,    75,    25,    78,    25,    25,
    61,    25,    25,    25,    25,    25,    25,    25,   nil,    29,
   nil,    29,    29,    75,    29,    29,    29,    29,    29,    29,
    29,    43,   nil,    43,    43,    25,    43,    43,    43,    43,
    43,    43,    43,   nil,    44,   nil,    44,    44,    29,    44,
    44,    44,    44,    44,    44,    44,    13,   nil,    13,    13,
    43,    13,    13,    13,    13,    13,    13,    13,   nil,    37,
   nil,    37,    37,    44,    37,    37,    37,    37,    37,    37,
    37,    38,   nil,    38,    38,    13,    38,    38,    38,    38,
    38,    38,    38,   nil,    39,   nil,    39,    39,    37,    39,
    39,    39,    39,    39,    39,    39,    40,   nil,    40,    40,
    38,    40,    40,    40,    40,    40,    40,    40,   nil,    27,
   nil,    27,    27,    39,    27,    27,    27,    27,    27,    27,
    27,    30,   nil,    30,    30,    40,    30,    30,    30,    30,
    30,    30,    30,   nil,    31,   nil,    31,    31,    27,    31,
    31,    31,    31,    31,    31,    31,    32,   nil,    32,    32,
    30,    32,    32,    32,    32,    32,    32,    32,   nil,    33,
   nil,    33,    33,    31,    33,    33,    33,    33,    33,    33,
    33,    34,   nil,    34,    34,    32,    34,    34,    34,    34,
    34,    34,    34,   nil,    35,   nil,    35,    35,    33,    35,
    35,    35,    35,    35,    35,    35,    36,   nil,    36,    36,
    34,    36,    36,    36,    36,    36,    36,    36,   nil,    45,
    47,    65,    47,    35,    47,    47,    47,    47,    47,    47,
    47,    47,    47,    47,    47,    36,    45,    65,   nil,     3,
    47,     3,     3,     3,     3,     3,     3,     3,     3,     3,
     3,     3,    59,   nil,    59,    59,    41,     3,    41,    41,
    41,    41,    41,    41,    41,    41,    41,    41,    41,   nil,
    59,   nil,    41,    49,    41,    49,    49,    49,    49,    49,
    49,    49,    49,    49,    49,    49,    60,   nil,    60,    60,
    51,    49,    51,    51,    51,    51,    51,    51,    51,    51,
    51,    51,    51,   nil,    60,   nil,   nil,    52,    51,    52,
    52,    52,    52,    52,    52,    52,    52,    52,    52,   nil,
   nil,   nil,   nil,   nil,    53,    52,    53,    53,    53,    53,
    53,    53,    53,    53,    55,   nil,    55,    55,    55,    55,
   nil,    54,    53,    54,    54,    54,    54,    54,    54,    54,
    54,    56,    55,    56,    56,    56,    56,   nil,    57,    54,
    57,    57,    57,    57,   nil,   nil,   nil,   nil,    58,    56,
    58,    58,    58,    58,   nil,   nil,    57,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    66,    58,    66,    66,    66,
    66,    66,    66,    66,    66,    66,    66,    66,   nil,   nil,
   nil,   nil,    67,    66,    67,    67,    67,    67,    67,    67,
    67,    67,    67,    67,    67,   nil,   nil,   nil,   nil,   nil,
    67,    80,    80,    80,    80,    80,    80,    80,    80,    80,
    80,    80,   nil,   nil,   nil,   nil,   nil,    80 ]

racc_action_pointer = [
    40,    33,     7,   313,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   144,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    -4,    10,    26,    17,    94,    67,   207,    56,   107,
   219,   232,   244,   257,   269,   282,   294,   157,   169,   182,
   194,   330,    52,   119,   132,   295,    52,   296,   nil,   347,
     1,   364,   381,   398,   415,   408,   425,   432,   442,   326,
   360,    66,    21,   nil,    -5,   295,   459,   476,   nil,    24,
    10,   nil,   nil,    -2,   nil,    82,    -6,   nil,    64,    56,
   493,    20,    23,   nil,   nil,   nil,   nil ]

racc_action_default = [
    -1,   -53,    -2,    -3,    -6,    -7,    -8,    -9,   -10,   -11,
   -12,   -13,   -14,   -53,   -16,   -17,   -18,   -19,   -20,   -21,
   -22,   -23,   -42,   -53,   -53,   -53,   -53,    -5,   -53,   -53,
   -53,   -53,   -53,   -53,   -53,   -53,   -53,   -53,   -53,   -53,
   -53,   -53,   -27,   -53,   -53,   -53,   -53,   -53,    87,    -4,
   -25,   -30,   -31,   -32,   -33,   -34,   -35,   -36,   -37,   -38,
   -39,   -40,   -41,   -15,   -28,   -53,   -43,   -44,   -45,   -47,
   -53,   -50,   -51,   -27,   -24,   -53,   -53,   -48,   -53,   -53,
   -29,   -53,   -53,   -52,   -26,   -46,   -49 ]

racc_goto_table = [
    27,     2,    41,    68,    71,    72,    65,     1,    76,   nil,
   nil,   nil,   nil,   nil,    47,   nil,    49,   nil,    51,    52,
    53,    54,    55,    56,    57,    58,    59,    60,    61,    62,
   nil,   nil,    66,    67,   nil,   nil,   nil,    79,   nil,    85,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    27,   nil,    80,   nil,   nil,   nil,   nil,   nil,
   nil,    78,   nil,   nil,   nil,   nil,    27 ]

racc_goto_check = [
     4,     2,     3,    14,    14,    14,    13,     1,    15,   nil,
   nil,   nil,   nil,   nil,     3,   nil,     3,   nil,     3,     3,
     3,     3,     3,     3,     3,     3,     3,     3,     3,     3,
   nil,   nil,     3,     3,   nil,   nil,   nil,    13,   nil,    14,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,     4,   nil,     3,   nil,   nil,   nil,   nil,   nil,
   nil,     2,   nil,   nil,   nil,   nil,     4 ]

racc_goto_pointer = [
   nil,     7,     1,   -11,    -2,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   -36,   -42,   -61 ]

racc_goto_default = [
   nil,   nil,    64,     3,     4,     5,     6,     7,     8,     9,
    10,    11,    12,   nil,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  0, 36, :_reduce_1,
  1, 36, :_reduce_2,
  1, 37, :_reduce_3,
  3, 37, :_reduce_4,
  2, 37, :_reduce_5,
  1, 37, :_reduce_6,
  1, 38, :_reduce_none,
  1, 38, :_reduce_none,
  1, 38, :_reduce_none,
  1, 38, :_reduce_none,
  1, 38, :_reduce_none,
  1, 38, :_reduce_none,
  1, 38, :_reduce_none,
  1, 38, :_reduce_none,
  3, 38, :_reduce_15,
  1, 39, :_reduce_none,
  1, 39, :_reduce_none,
  1, 40, :_reduce_18,
  1, 40, :_reduce_19,
  1, 40, :_reduce_20,
  1, 40, :_reduce_21,
  1, 40, :_reduce_22,
  1, 41, :_reduce_23,
  4, 41, :_reduce_24,
  3, 41, :_reduce_25,
  6, 41, :_reduce_26,
  0, 48, :_reduce_27,
  1, 48, :_reduce_28,
  3, 48, :_reduce_29,
  3, 42, :_reduce_30,
  3, 42, :_reduce_31,
  3, 42, :_reduce_32,
  3, 42, :_reduce_33,
  3, 42, :_reduce_34,
  3, 42, :_reduce_35,
  3, 42, :_reduce_36,
  3, 42, :_reduce_37,
  3, 42, :_reduce_38,
  3, 42, :_reduce_39,
  3, 42, :_reduce_40,
  3, 42, :_reduce_41,
  1, 43, :_reduce_42,
  3, 44, :_reduce_43,
  3, 44, :_reduce_44,
  3, 45, :_reduce_45,
  6, 45, :_reduce_46,
  0, 50, :_reduce_47,
  1, 50, :_reduce_48,
  3, 50, :_reduce_49,
  3, 46, :_reduce_50,
  3, 47, :_reduce_51,
  3, 49, :_reduce_52 ]

racc_reduce_n = 53

racc_shift_n = 87

racc_token_table = {
  false => 0,
  :error => 1,
  :IF => 2,
  :ELSE => 3,
  :PROCESS => 4,
  :CLASS => 5,
  :NEWLINE => 6,
  :NUMBER => 7,
  :STRING => 8,
  :TRUE => 9,
  :FALSE => 10,
  :NIL => 11,
  :IDENTIFIER => 12,
  :CONSTANT => 13,
  :INDENT => 14,
  :DEDENT => 15,
  "." => 16,
  "!" => 17,
  "*" => 18,
  "/" => 19,
  "+" => 20,
  "-" => 21,
  ">" => 22,
  ">=" => 23,
  "<" => 24,
  "<=" => 25,
  "==" => 26,
  "!=" => 27,
  "&&" => 28,
  "=" => 29,
  "," => 30,
  "(" => 31,
  ")" => 32,
  ";" => 33,
  "||" => 34 }

racc_nt_base = 35

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "IF",
  "ELSE",
  "PROCESS",
  "CLASS",
  "NEWLINE",
  "NUMBER",
  "STRING",
  "TRUE",
  "FALSE",
  "NIL",
  "IDENTIFIER",
  "CONSTANT",
  "INDENT",
  "DEDENT",
  "\".\"",
  "\"!\"",
  "\"*\"",
  "\"/\"",
  "\"+\"",
  "\"-\"",
  "\">\"",
  "\">=\"",
  "\"<\"",
  "\"<=\"",
  "\"==\"",
  "\"!=\"",
  "\"&&\"",
  "\"=\"",
  "\",\"",
  "\"(\"",
  "\")\"",
  "\";\"",
  "\"||\"",
  "$start",
  "Root",
  "Expressions",
  "Expression",
  "Terminator",
  "Literal",
  "Call",
  "Operator",
  "Constant",
  "Assign",
  "Process",
  "Class",
  "If",
  "ArgList",
  "Block",
  "ParamList" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'grammar.y', 42)
  def _reduce_1(val, _values, result)
     result = Nodes.new([])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 43)
  def _reduce_2(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 49)
  def _reduce_3(val, _values, result)
     result = Nodes.new(val)
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 50)
  def _reduce_4(val, _values, result)
     result =  val[0] << val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 52)
  def _reduce_5(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 53)
  def _reduce_6(val, _values, result)
     result = Nodes.new([])
    result
  end
.,.,

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

# reduce 13 omitted

# reduce 14 omitted

module_eval(<<'.,.,', 'grammar.y', 67)
  def _reduce_15(val, _values, result)
     result = val[1]
    result
  end
.,.,

# reduce 16 omitted

# reduce 17 omitted

module_eval(<<'.,.,', 'grammar.y', 79)
  def _reduce_18(val, _values, result)
     result = NumberNode.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 80)
  def _reduce_19(val, _values, result)
     result = StringNode.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 81)
  def _reduce_20(val, _values, result)
     result = TrueNode.new
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 82)
  def _reduce_21(val, _values, result)
     result = FalseNode.new
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 83)
  def _reduce_22(val, _values, result)
     result = NilNode.new
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 89)
  def _reduce_23(val, _values, result)
     result = CallNode.new(nil, val[0], [])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 91)
  def _reduce_24(val, _values, result)
     result = CallNode.new(nil, val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 93)
  def _reduce_25(val, _values, result)
     result = CallNode.new(val[0], val[2], [])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 96)
  def _reduce_26(val, _values, result)
     result = CallNode.new(val[0], val[2], val[4])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 101)
  def _reduce_27(val, _values, result)
     result = []
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 102)
  def _reduce_28(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 103)
  def _reduce_29(val, _values, result)
     result = val[0] << val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 108)
  def _reduce_30(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 109)
  def _reduce_31(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 110)
  def _reduce_32(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 111)
  def _reduce_33(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 112)
  def _reduce_34(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 113)
  def _reduce_35(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 114)
  def _reduce_36(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 115)
  def _reduce_37(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 116)
  def _reduce_38(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 117)
  def _reduce_39(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 118)
  def _reduce_40(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 119)
  def _reduce_41(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 124)
  def _reduce_42(val, _values, result)
     result = GetConstantNode.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 130)
  def _reduce_43(val, _values, result)
     result = SetLocalNode.new(val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 131)
  def _reduce_44(val, _values, result)
     result = SetConstantNode.new(val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 137)
  def _reduce_45(val, _values, result)
     result = ProcessNode.new(val[1], [], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 139)
  def _reduce_46(val, _values, result)
     result = ProcessNode.new(val[1], val[3], val[5])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 144)
  def _reduce_47(val, _values, result)
     result = []
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 145)
  def _reduce_48(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 146)
  def _reduce_49(val, _values, result)
     result = val[0] << val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 152)
  def _reduce_50(val, _values, result)
     result = ClassNode.new(val[1], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 158)
  def _reduce_51(val, _values, result)
     result = IfNode.new(val[1], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 164)
  def _reduce_52(val, _values, result)
     result = val[1]
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class Parser
